package org.ual.hmis.BravoDahbi;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.firefox.FirefoxOptions;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class RegistrodeusuarioCasocorrectoTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() throws Exception {
//    System.setProperty("webdriver.gecko.driver", "drivers/geckodriver.exe");
//    System.setProperty("webdriver.chrome.driver", "drivers/chromedriver.exe");

    FirefoxOptions firefoxOptions = new FirefoxOptions();
    firefoxOptions.setHeadless(true);
    driver = new FirefoxDriver(firefoxOptions);

//    ChromeOptions chromeOptions = new ChromeOptions();
//    chromeOptions.setHeadless(true);
//    driver = new ChromeDriver(chromeOptions);

//    driver = new HtmlUnitDriver(BrowserVersion.FIREFOX_68,true);

    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
}
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void registrodeusuarioCasocorrecto() {
    driver.get("http://sepultura.northeurope.cloudapp.azure.com:1337/");
    driver.findElement(By.linkText("Sign up")).click();
    vars.put("emailrandom", js.executeScript("return \"ual-\" + Math.floor(Math.random()*1500000)+\"@ual.es\""));
    System.out.println(vars.get("emailrandom").toString());
    driver.findElement(By.id("full-name")).sendKeys("User-random");
    driver.findElement(By.id("email-address")).click();
    driver.findElement(By.id("email-address")).sendKeys(vars.get("emailrandom").toString());
    driver.findElement(By.id("password")).click();
    driver.findElement(By.id("password")).sendKeys("marche4");
    driver.findElement(By.id("confirm-password")).click();
    driver.findElement(By.id("confirm-password")).sendKeys("marche4");
    driver.findElement(By.id("terms-agreement")).click();
    driver.findElement(By.cssSelector(".ajax-button")).click();
    try {
        Thread.sleep(1000);
      } catch (InterruptedException e) {
        e.printStackTrace();
      }
    driver.findElement(By.id("header-account-menu-link")).click();
    driver.findElement(By.linkText("Sign out")).click();
    driver.findElement(By.cssSelector(".logo")).click();
    driver.manage().window().setSize(new Dimension(1382, 744));
  }
}
